spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: iampratikHP@14

spring:
  jpa:
    hibername:
      ddl-auto: update
    database-platform: